### ISSUE TITLE
App crashed when I  clicked on Imported file from spreadsheet.

### ISSUE THREAD

**Issue by cckole** [Chooloo/call_manage#25]
### Descriptions
After selecting the XLS file from my document/device, I was able to import contacts from spread sheet. But clicking on the exported file made the app to crash
### Expected behavior
I expected the file to open when I clicked on it after importing from spread sheet.
### Steps to reproduce
-	Launch the app
-	Swipe or click on the `Excel`
-	Fill the blank spaces and select a file to import
-	Click on done
-	After the file has been imported, click on it and note the error.

### Reproducing the bug
https://youtu.be/NmjwqPKsvN8
### Device used

- Tecno spark K7
- Android 7.0

### Logcat

```at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
06-16 12:25:52.825 32716 32716 E AndroidRuntime: FATAL EXCEPTION: main
06-16 12:25:52.825 32716 32716 E AndroidRuntime: Process: com.chooloo.www.callmanager, PID: 32716
06-16 12:25:52.825 32716 32716 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chooloo.www.callmanager/com.chooloo.www.callmanager.ui.activity.OngoingCallActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
06-16 12:25:52.825 32716 32716 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
06-16 12:25:52.825 32716 32716 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
06-16 12:25:52.825 32716 32716 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
06-16 12:25:52.825 32716 32716 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
06-16 12:25:52.825 32716 32716 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
06-16 12:25:52.825 32716 32716 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
06-16 12:25:52.825 32716 32716 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6251)
06-16 12:25:52.825 32716 32716 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-16 12:25:52.825 32716 32716 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
06-16 12:25:52.825 32716 32716 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
06-16 12:25:52.825 32716 32716 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
06-16 12:25:52.825 32716 32716 E AndroidRuntime: 	at com.chooloo.www.callmanager.util.CallManager.getDisplayContact(CallManager.java:221)
06-16 12:25:52.825 32716 32716 E AndroidRuntime: 	at com.chooloo.www.callmanager.ui.activity.OngoingCallActivity.displayInformation(OngoingCallActivity.java:522)
06-16 12:25:52.825 32716 32716 E AndroidRuntime: 	at com.chooloo.www.callmanager.ui.activity.OngoingCallActivity.onCreate(OngoingCallActivity.java:199)
06-16 12:25:52.825 32716 32716 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6670)
06-16 12:25:52.825 32716 32716 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
06-16 12:25:52.825 32716 32716 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
06-16 12:25:52.825 32716 32716 E AndroidRuntime: 	... 9 more```

**Comment by roeiedri** [comment]
The format of the excel file should be a column of phone numbers and a column of the contacts names
In the contact number and number column fields u should enter the number of the column of each one
For example lets say the file looks like this:
number1 | name1
number2 | name2
number3 | name3

In the input fields u should enter 1 and 2
1 for the number column field and 2 for the contacts column field

I would appreciate if u can try this and tell me if the issue still occurs

Btw, sorry for the crazy delay, we don't really have the time to support the app unfortunately
