### ISSUE TITLE
Koler V0.2.7 Crashes When A Number Is Pressed While On A Call

### ISSUE THREAD

**Issue by realrufans** [Chooloo/call_manage#4]
#### Expected behavior
I expected Koler not to crash when a user types a number while dialing a call.

#### Actual behavior

It crashes immediately after pressing the first number.

#### How to reproduce

- dial a number
<Sup> ( mute, pause, loud speaker, an option to dial a number, and a + sign button will pop up.)</Sup>

- Click on the option to dial a number

- Type a  number

- Watch the app crash 

* Browser/App version:
Koler v0.27

* Operating system:
Android 0

#### Recording Of The Bug

![MNML-May15-1145-1557917215368.gif](https://cdn.steemitimages.com/DQmUdbeo6zHxFXjrgwfeBFrMGLsqncBaWa1GT6zhwMvkWrL/MNML-May15-1145-1557917215368.gif)

**Comment by realrufans** [comment]
I will provide a logcat when  I'm on my AS.

**Comment by roeiedri** [comment]
Thank you very muchSent from my Samsung Galaxy smartphone.
-------- Original message --------From: solomon stephen <notifications@github.com> Date: 5/15/19  14:05  (GMT+02:00) To: Chooloo/call_manage <call_manage@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [Chooloo/call_manage] Koler V0.2.7 Crashes When A Number Is Pressed While On A Call (#4) I will provide a logcat when  I'm on my AS.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Chooloo/call_manage/issues/4?email_source=notifications\u0026email_token=AF574R6LRTGK3CHL5EOFH6DPVPU7VA5CNFSM4HNCE2UKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVOJ62A#issuecomment-492609384",
"url": "https://github.com/Chooloo/call_manage/issues/4?email_source=notifications\u0026email_token=AF574R6LRTGK3CHL5EOFH6DPVPU7VA5CNFSM4HNCE2UKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVOJ62A#issuecomment-492609384",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by realrufans** [comment]
Here's the crash Log

```2019-05-15 16:47:28.995 31209-31209/com.chooloo.www.callmanager E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.chooloo.www.callmanager, PID: 31209
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.telecom.Call.playDtmfTone(char)' on a null object reference
        at com.chooloo.www.callmanager.util.CallManager.keypad(CallManager.java:108)
        at com.chooloo.www.callmanager.ui.activity.OngoingCallActivity.lambda$onCreate$2(OngoingCallActivity.java:304)
        at com.chooloo.www.callmanager.ui.activity.-$$Lambda$OngoingCallActivity$iL9ptpUuP7OEHn93SAfMj0buAE0.onChanged(Unknown Source:2)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:113)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:131)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:289)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at com.chooloo.www.callmanager.viewmodels.SharedDialViewModel.setNumber(SharedDialViewModel.java:32)
        at com.chooloo.www.callmanager.ui.fragment.DialerFragment.setNumber(DialerFragment.java:220)
        at com.chooloo.www.callmanager.ui.fragment.DialerFragment.addChar(DialerFragment.java:120)
        at com.chooloo.www.callmanager.ui.fragment.DialerFragment_ViewBinding$11.doClick(DialerFragment_ViewBinding.java:137)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
        at android.view.View.performClick(View.java:6748)
        at android.view.View$PerformClick.run(View.java:25458)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6524)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)
```
